# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/progress_tracker
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ????????? ????????????? SQL (schema.sql)
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql

# Spring Boot App Configuration
spring.application.name=progress-tracker
server.port=8080

# Logging Configuration
logging.level.root=INFO
logging.level.com.ramis.progresstracker=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Jackson Configuration
spring.jackson.serialization.indent-output=true
spring.jackson.time-zone=Europe/Moscow
spring.jackson.locale=ru_RU
